### ISSUE TITLE
Welcome to submit any questions here

### ISSUE THREAD

**Issue by Sunpeisen** [Sunpeisen/CircCode#1]
Dear users, 
If you encounter any problems/bugs/doubts during use, or if you have any suggestions, you are welcome to submit them here to help us better improve CircCode.

Thank you for your using.
：）

**Comment by PSSUN** [comment]
Our tools have just been released, and the amount of data tested by CircCode is not large enough. If you encounter any problems during the operation, you are welcome to leave valuable comments, we will correct the first time!

我们的工具刚刚发布，CircCode进行的测试的数据量还不够大。如果您在运行中遇到任何问题，欢迎您留下宝贵意见，我们将第一时间进行改正！

ツールがリリースされたばかりで、CircCodeによってテストされたデータの量は十分ではありません。 操作中に問題が発生した場合は、貴重なコメントを残してください。最初に修正します！

Unsere Tools wurden gerade veröffentlicht, und die von CircCode getestete Datenmenge ist nicht groß genug. Sollten Sie während der Operation auf Probleme stoßen, können Sie gerne wertvolle Kommentare hinterlassen, die wir beim ersten Mal korrigieren!

Наши инструменты только что были выпущены, и объем данных, протестированных CircCode, недостаточно велик. Если у вас возникнут какие-либо проблемы во время операции, вы можете оставить ценные комментарии, мы исправим с первого раза!

**Comment by Tanv1** [comment]
15447
15448
15449
15450
15451
Error in (function (edges, n = max(edges), directed = TRUE) :
At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value
Calls: classification -> createNet -> graph -> do.call ->
In addition: Warning message:
In max(edges) : no non-missing arguments to max; returning -Inf
Execution halted
Classify successfully!
sed: can't read /path/to/my_directory/CircCode_tem/ERR45678Aligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa: No such file or directory
Traceback (most recent call last):
File "find_RCRJ_and_classify.py", line 369, in
main()
File "find_RCRJ_and_classify.py", line 355, in main
classify(coding_seq,
File "find_RCRJ_and_classify.py", line 102, in classify
seqs = SeqIO.parse(final_trans_file, 'fasta')
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/init.py", line 607, in parse
return iterator_generator(handle)
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 183, in init
super().init(source, mode="t", fmt="Fasta")
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 47, in init
self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/my_directory/CircCode_tem/ERR45678Aligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa'

Help needed!

**Comment by Tanv1** [comment]
15447
15448
15449
15450
15451
Error in (function (edges, n = max(edges), directed = TRUE) :
At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value
Calls: classification -> createNet -> graph -> do.call ->
In addition: Warning message:
In max(edges) : no non-missing arguments to max; returning -Inf
Execution halted
Classify successfully!
sed: can't read /path/to/my_directory/CircCode_tem/ERR45678Aligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa: No such file or directory
Traceback (most recent call last):
File "find_RCRJ_and_classify.py", line 369, in
main()
File "find_RCRJ_and_classify.py", line 355, in main
classify(coding_seq,
File "find_RCRJ_and_classify.py", line 102, in classify
seqs = SeqIO.parse(final_trans_file, 'fasta')
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/init.py", line 607, in parse
return iterator_generator(handle)
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 183, in init
super().init(source, mode="t", fmt="Fasta")
File "/home/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 47, in init
self.stream = open(source, "r" + mode)
**FileNotFoundError: [Errno 2] No such file or directory: '/path/to/my_directory/CircCode_tem/ERR45678Aligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa'**

Help needed!
